name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest

      - name: Deploy to PythonAnywhere
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          curl -u "$PYTHONANYWHERE_USERNAME:$PYTHONANYWHERE_API_TOKEN" \
          https://www.pythonanywhere.com/api/v0/user/$PYTHONANYWHERE_USERNAME/webapps/yourusername.pythonanywhere.com/reload/
